apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoreact-deployment
spec:
  selector:
    matchLabels:
      app: todoreact
  replicas: 3
  template:
    metadata:
      labels:
        app: todoreact
    spec:
     containers:
     - name: todoreact
       image: jeanossa/todoreact:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 80